global using BuildingBlocks.Behaviours;
global using Operations.API.Models;
global using Operations.API.Persistence;
global using BuildingBlocks.Exceptions.Handler;
global using FluentValidation;
global using Carter;
global using MediatR;
global using Mapster;
global using Marten;
