parameters:
- name: 'stage'
  type: string
- name: 'displayName'
  type: string
- name: 'environment'
  type: string
- name: 'microserviceName'
  type: string
- name: 'ingress'
  type: string
  default: 'internal'
- name: 'dependsOn'
  type: string
  default: Build

stages:
- stage: ${{ parameters.stage }}
  displayName: ${{ parameters.displayName }}
  dependsOn: ${{ parameters.dependsOn }}
  jobs:
  - deployment: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureContainerApps@1
            inputs:
              azureSubscription: 'Azure subscription 1(ac6df0a6-4361-4fcc-b232-1c938d623a03)'
              imageToDeploy: 'transportacr.azurecr.io/${{ parameters.microserviceName }}:$(Build.BuildId)'
              containerAppName: '${{ parameters.microserviceName }}-container-app'
              resourceGroup: 'transport-microservices-rg'
              containerAppEnvironment: 'transport-microservices-env-prod' # TODO: This shouldn't have the prod environment in its name.
              targetPort: '8080'
              location: 'uksouth'
              ingress: ${{ parameters.ingress }}
              acrName: 'transportacr'