trigger:
  branches:
    include:
      - master
  paths:
    include:
      - src/Services/Suppliers/Suppliers.API/*

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '6df85c80-9463-489d-bf10-2e4ec454e7aa'
  imageRepository: 'suppliersapi'
  containerRegistry: 'transportacr.azurecr.io'
  dockerfilePath: 'src/Services/Suppliers/Suppliers.API/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'transportacr1345436e-auth'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        buildContext: $(Build.SourcesDirectory)/src
        tags: |
          $(tag)

- template: templates/deploy-aca.yaml
  parameters:
    stage: 'Staging'
    displayName: 'Deploy to staging'
    environment: 'staging'
    microserviceName: 'suppliersapi'
    dependsOn: 'Build'

- template: templates/deploy-aca.yaml
  parameters:
    stage: 'Production'
    displayName: 'Deploy to production'
    environment: 'production'
    microserviceName: 'suppliersapi'
    dependsOn: 'Staging'