apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: operationsapi
  name: operationsapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: operationsapi
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: operationsapi
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ASPNETCORE_HTTPS_PORTS
              value: "8081"
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ConnectionStrings__AzureDatabase
              value: Server=operationsdb;Port=5432;Database=OperationsDb;User Id=postgres;Password=postgres;Include Error Detail=true
            - name: ConnectionStrings__LocalDatabase
              value: Server=operationsdb;Port=5432;Database=OperationsDb;User Id=postgres;Password=postgres;Include Error Detail=true
          image: operationsapi
          name: operationsapi
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
          volumeMounts:
            - mountPath: /home/app/.aspnet/https
              name: operationsapi-cm1
              readOnly: true
      restartPolicy: Always
      volumes:
        - configMap:
            name: operationsapi-cm1
          name: operationsapi-cm1
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: operationsapi
  name: operationsapi
spec:
  ports:
    - name: "6101"
      port: 6101
      targetPort: 8080
    - name: "6161"
      port: 6161
      targetPort: 8081
  selector:
    io.kompose.service: operationsapi
---
apiVersion: v1
binaryData:
  Operations.API.pfx: TUlJS1dBSUJBekNDQ2hRR0NTcUdTSWIzRFFFSEFhQ0NDZ1VFZ2dvQk1JSUovVENDQmU0R0NTcUdTSWIzRFFFSEFhQ0NCZDhFZ2dYYk1JSUYxekNDQmRNR0N5cUdTSWIzRFFFTUNnRUNvSUlFN2pDQ0JPb3dIQVlLS29aSWh2Y05BUXdCQXpBT0JBZ3hGSFBmT1pkTWNnSUNCOUFFZ2dUSWoveVNPejRMSXJHM1krMU5sRWJuRjFTNFl4Y1V1d2RNME5WLysrbGl3Y3dCdSticWNYYng3MU1qVktkOEY1cmhjZGpoa0hPVVorZ3l4NHNHeDBDZFF1akxUaEh3SENWOFhwZ0d1RVRBbkxtSmxvMm9lYUtqajFMU1lPWGtLK3NmZFFmYVA0Q1dqVC9PZHRTY3lSQ3drbFhLUXhqcHBBdURUY0ZvZFlDd3pLeXJDSytIS0MrT3pYZk5wZVBqR2l3a255RE1ieVlPY2ZOUmNMVXZDUGNXNDJrV2pqazFSZGhXYXhCWTIvVVl5anNocmFLMjUxamZzNWs3TzFCbGNLRUE3bWNmR1NZaVZIWjhtOXcvM0FKamlTT3N6a3B1RnBjVFc0eHdsV0FZZlBLclpNYlI0b0sxWFBUb0pjdjBlNEpqYndwNnQyN1VDYVEwTnBwQ3Fvam1ZL0FBZVdFTi9LUUtMZW9yaFJJdHVPQTBWUWErdmVod2dadndZT1kzUnczTytDaXQ4WEVPWEhhR0ZPMlZGd0g1TG12NE00TWFVRHY3cjUzR0NHQmE5eVpQVnFyZFRXbEp3SzRBM0hPVUh1cU1OWGFXeG40eGFkRzNCQ0VDODlnTThLTThIMzE5VTVIUXlhUGdPRUttNVdMcXFKblF4dk9lZGhlZlg5aGtkOTlJTHIzM3pJVTdhNFZKNnY5ZktRZ0dWZmhVT1pZWVA5VE9idzZBS3VLaFRqZ3VHUVkyQnIxVGQzOVltTkFwM1hXc2xBWlk4Z2lVb1JGS2R2VDhDWkl2SnJwWkJsaityUTNkQzZJbW1LTDQyaEd5Snl6NXI5c3NNZGRkMlJPSGJOM1VlWDRuRVRLRWpTanhuREtqZUh2Y3R5WVpwNWt6RzgxV3VYTkJBSExOMkxITzJtWDBmZ01aNnAzMDhodXFrVmJWbUcvK2lOZnlobm9vYnNmSm9DRmhUMjN2OXRZRGZIbnk4dnFlZGN4Skl6eHUrMWlsdUh3R005WFBYd1o5eG05QnBhZ0wxWDYvdXhrZjJRbmcwNjllKzd0MXlVSEVUdXJxamV6cm5sYXd5N1dDL29sMExzY1FvUTgvQWhWKzh4VTZ6d1ZkeW92RlpxZWFjRTJrWUNtdVhyVFRMVkhETG9HK3ZKY1lVQlFYcngyK0IrV0t3blNBQ2NHZEJBbTRFbWVoNE1qY3k4T0pzVStIbW9sSnZreDMxbjlOSVdjOGVkL01VTU5uV0lya0NNbGllM1NRQW5SRThOTnV1NlBscDM1Qk5NS0dvdUh6NVlRTTduaU1wSUxGTEhMd2ZFbnc5QTVXUjVYVVdXL1VXTzNhaEc5bWxHTjh1Z0pVK3hmRXJYMHFYQnUrbWNaTlZVZ2VNblFqL1dkUlY1SUE4M0xZM0ZzNm5pNmJiSzBVNXdkYUdKenZYM1NiVWx2dnozZElNcXI0dHFjNzlPM3JvV0xmNEcxTTdRSUZlcnczWHUrQ0VFYzNtbHV0WHBxMkgwVFhIaWoxTm8yT0ZFeENUNENNczU1aW0waDQwbjh6d3pUMVAwcFVuQ0gvMENBckxiNHhnMDJsNnF0TjlReVlyU2p3ZmR2cTYwb1VKVFJsOE9aTS9LZ2JLT05zdVMwS0FIb3NBanlEYkhLd2hNVzZoeVk4OXVGNmREZmRaanNncThUZ29LOEtKK3daOWYyQjVQMFZSRFhsMVIyT0JVL0FjTDNkbXNOVDR2dTYyYXhUVUVjUnNqWDFiVlBCREJ6MHByeVdwSGxjeVQxelc0VkN0b0g1NU1xUjFPa2ZrYXUvR0UxWjNBeHJpRUZGNGl5UjVlMmVkVDRhRFFvREY5UUJhclovbUM0U2o4THp2OWpaTDcvY296dXo3c0paS09MemwzNnFKSlp1b1BjY2NpQVhLTHE5UHQ0Slg4bVB3MTUzaGhoWjlKdEVKanFPaHpFcEpWYXUzcTFEN0VWM2lKbzMzY2dZYkJ5cG5uWFd5TmtPcmpLUU0rVlZxTklYbndzTWlEaUlYYjM5VkE5NmVCZ3FSMForbEE2MnFlOEVaY2FhcjZwOW5BS0VObkpXZDBZUWcxWGtqbFJxcTRWd05KTDRTbVV3Q1VtZDdVeVJVaUd1OUJZakt3SGppMXJvLzJKa1ZGL1VQSFhLR0puaXZqajFPZCsyaG9VdE1ZSFJNQk1HQ1NxR1NJYjNEUUVKRlRFR0JBUUJBQUFBTUZzR0NTcUdTSWIzRFFFSkZERk9Ia3dBZXdBNUFEa0FOQUJGQUVRQU9RQTNBRVVBTFFCRkFFVUFNd0E1QUMwQU5BQkZBRUVBTWdBdEFEa0FPQUEyQURJQUxRQXhBREFBUWdBeEFESUFOUUE0QUVZQU1nQkdBREFBTVFCOU1GMEdDU3NHQVFRQmdqY1JBVEZRSGs0QVRRQnBBR01BY2dCdkFITUFid0JtQUhRQUlBQlRBRzhBWmdCMEFIY0FZUUJ5QUdVQUlBQkxBR1VBZVFBZ0FGTUFkQUJ2QUhJQVlRQm5BR1VBSUFCUUFISUFid0IyQUdrQVpBQmxBSEl3Z2dRSEJna3Foa2lHOXcwQkJ3YWdnZ1A0TUlJRDlBSUJBRENDQSswR0NTcUdTSWIzRFFFSEFUQWNCZ29xaGtpRzl3MEJEQUVETUE0RUNFMjUxWXVwMWtQWUFnSUgwSUNDQThDdnJOVFpWcElmOS9GaDR4Z3Z6V05vWTVhZWZickR4a2FDbk11aGcyT2FMNGhMV1dGellLMC93R3VvcTU5bldIaFREb0Q0V0N1SDF6UVV2ZGNQaWk1R2E2aFVIR0hKOU5GeVpjY0VjeEJYMW0ycTlDeHF3UWR3K0Y1SWlCejlhcnJCcnVKWDhUeG9oaW9pTFdLRXJJbWRYZnU3cGZ5NkZlaFg2aVovV0V5RTBHS05mbE10VlJ2Y1VhQlpZQXQ0M01tOTd2UWhrV0I1RmFEOEZ5VnV0SWY3OFducEVMWGVSeVdNL0dJUFhMMkdMSzhsOHB0dXp6a2FYeGY1ellUSXlvNXNDbktDNW1OcUhWL003RVBEeFhoUi92UFdReWJ2ZjIyK0lCRklWRzRBaXNJaG80bHR3MVVaNW54UXdveTVhTDNUdkV4OWpXQmhwM3Voa1A5OUJiNEVlRmRBWElPNXlOM0puUEoyYURrbTFZOE91bDBNZGc2OUlCQStPRmZKMG5lb0xSRmNoWE9majNXbHlkdFMvamQ2eEhSWnpUVnV1RjhNTVdwNERoeTZqMjdBN28vQVRyKzA2RHpTQ21PUjB4Uno3WDZyaGJuVWxVNkRqRmVvWjRER1lBZDlqRCtPbURteEtCQVErdUs3bGppalg0KzZaajE3R3JFOWREUUliSmRSWHZLWEh5ZDBaazZMd2pYVnM2NzBCa2JTRkQzWUl0VnRSaVhJa3lJNTMyeGN6U2tRT1NDanBkOXNTb0ZDS0UrQWFkS29iSWlDTFVZUmVVdGpmVnllR1NyblBDUVRFV1JhSm5US3dDK1MyZjF2UDM3cXlTZFhnWFN3UW5OWG9TemdBeXNPVlhVU1ZUN3dyWHVTeGxNVWg5bXV4OXJ3aXVleUVJRUI2NnhZNlp5UU5ZTWhDMVpYNU5pVzJ0RFROUGRkeXFrSlZhRm1xVW53b0VXSGVuaUloMDV0ajQ4YkV2Y1pkbHp2TnN5NjVSVEZ0T01qdEltQjMyeGUvRVA0dUQ4enRKRUZFckM2TDRzU2gwdkJkRGdiQ3UwSzFTZnp6STVad0NRa3BOUDJtS2N5MkszTUJhd05lUzhEQU00d1ZzZkIxSlR4ZnBmell0VUV0TTFSQWRaRXFraFRRVTJ5eVZxYkc2bzcyUUxoZGp4VmJRMmFDU1A2RlJuN2E4b1VreWY4UXBrMU1jbGlFcGJnamM2ZWZJNDA2U1N3NHQyb01PaWpQZFNrM3BXS0ROR2dvRmZSZlNaZGE3dDFOZ0IwMkV1QTJyV3NmY0IwRXZqK2ZIVDJRc2hBaTl0QjhZZC91MDJhVWNpeFpvMndEV21LMXlhOXBGM211d2ZpTE5sUllzOFMycUlMeFdPMVdBa1pLWE1RSDloRGZIWFlLVm1MRUxEYW9KUzRyU01ubWw1bUgyYVZVUlZhNUpBZW9IMUZ6cERyRzl2QUgrTkx6ZnNPZUdac2R3UWdKaE5rZDE5T2gvamF3WjFadDk4dnF4SWFRSkhSY3h0WjB2SU5TZTVvay9JeXdTWTFIK0ZPalZaUmxlYVFGZ1lXMHhUcjdDZTRsdm9YcVdBT2RFRnRJTWUrbm0rN1YyTjJJN29IQmNVSDdjVnhodVNLTXZWYUVLWmJvT1poeVkvZ2RvdkVWM0ozeHdGTHk2b1J4WnpGYkVnYW9CUEhLUGV1dU8zRCt0MS85L1l3T3pBZk1BY0dCU3NPQXdJYUJCUUdwU2ROY3dyZXJkMEJnQkFXY3UzWHQ4NmZ3QVFVQWJMeGVETXZzaFZJWmFrQmo4Z3B1NUFiTFRjQ0FnZlE=
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: operationsapi
  name: operationsapi-cm1