apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: operationsapi
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ASPNETCORE_HTTPS_PORTS
              value: "8081"
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ConnectionStrings__AzureDatabase
              value: Server=operationsdb;Port=5432;Database=OperationsDb;User Id=postgres;Password=postgres;Include Error Detail=true
            - name: ConnectionStrings__LocalDatabase
              value: Server=operationsdb;Port=5432;Database=OperationsDb;User Id=postgres;Password=postgres;Include Error Detail=true
          image: operationsapi
          name: operationsapi
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
          volumeMounts:
            - mountPath: /home/app/.aspnet/https
              name: operationsapi-cm1
              readOnly: true
      restartPolicy: Always
      volumes:
        - configMap:
            name: operationsapi-cm1
          name: operationsapi-cm1
---
apiVersion: v1
kind: Service
spec:
  ports:
    - name: "6101"
      port: 6101
      targetPort: 8080
    - name: "6161"
      port: 6161
      targetPort: 8081
  selector:
    io.kompose.service: operationsapi
